# -*- coding: utf-8 -*-
"""Turn niuway_c5_checkin.xlsx into the two files the booth page is built from.

The sheet is one row per line item: a tent row, or an add-on row, sharing the
guest's address and OrderID. "Number of tickets sold" is the quantity, so a
single row can be two tents.

    python3 import_c5z.py

Writes c5z-bookings.csv (one line per tent) and c5z-addons.csv (one line per
add-on). Both are git-ignored — they carry real addresses.
"""
import csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
XLSX = os.path.join(os.path.dirname(HERE), "niuway_c5_checkin.xlsx")
AREA = "C5Z"
TENT = "Comfort Zelt "          # everything else with a C5Z suffix is an add-on


def qty(v):
    try:
        return int(v) if v not in (None, "") else 1
    except (TypeError, ValueError):
        return 1


def main():
    try:
        import openpyxl
    except ImportError:
        raise SystemExit("needs openpyxl:  python3 -m pip install openpyxl")
    ws = openpyxl.load_workbook(XLSX, data_only=True)["Tabelle1"]

    tents, addons, skipped = [], [], []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if not any(c is not None for c in r):
            continue
        order, pos, product, n, mail, checkin = (str(c).strip() if c is not None else "" for c in r[:6])
        if AREA not in product:
            continue
        if "@" not in mail:                      # "Naemi und Frederike" — held, not booked
            skipped.append((mail, product, checkin)); continue
        if product.startswith(TENT):
            kind = product[len(TENT):].replace(" " + AREA, "").strip()
            for _ in range(qty(n)):
                tents.append((mail.lower(), kind, order, checkin))
        else:
            name = product.replace(" " + AREA, "").replace("Comfort ", "").strip()
            addons.append((mail.lower(), name, qty(n), order))

    with open(os.path.join(HERE, "c5z-bookings.csv"), "w", newline="", encoding="utf-8") as f:
        f.write("# Generated by import_c5z.py from niuway_c5_checkin.xlsx — do not hand-edit.\n")
        f.write("# One line per tent: a guest with three tents has three lines.\n")
        w = csv.writer(f); w.writerow(["email", "tent_type", "order_id", "checkin"])
        for t in sorted(tents): w.writerow(t)

    with open(os.path.join(HERE, "c5z-addons.csv"), "w", newline="", encoding="utf-8") as f:
        f.write("# Generated by import_c5z.py from niuway_c5_checkin.xlsx — do not hand-edit.\n")
        w = csv.writer(f); w.writerow(["email", "addon", "qty", "order_id"])
        for a in sorted(addons): w.writerow(a)

    import collections
    print("c5z-bookings.csv — %d tents for %d guests"
          % (len(tents), len({t[0] for t in tents})))
    for kind, n in sorted(collections.Counter(t[1] for t in tents).items()):
        print("   %-12s %2d" % (kind, n))
    print("c5z-addons.csv   — %d add-on lines, %d items"
          % (len(addons), sum(a[2] for a in addons)))
    for name, n in sorted(collections.Counter(a[1] for a in addons).items()):
        print("   %-14s %2d lines" % (name, n))
    for mail, product, checkin in skipped:
        print("   held: %s — %s (%s)" % (checkin, product, mail))


if __name__ == "__main__":
    main()
